# This is an OpenAPI Specification (https://swagger.io/specification/)
# for gp-connect-appointments-management-fhir owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'gp-connect-appointments-management-fhir'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview

    ![Appointments Overview](https://raw.githubusercontent.com/NHSDigital/gp-connect-appointments-management-fhir/specification/diagrams/GP-Connect-PFS-Appointment-Management.svg)

    Use this API to book and manage patient appointments at their GP practice.

    You can:
     - retrieve a patientâ€™s appointments
     - search for free slots
     - get details of a single appointment
     - book an appointment
     - cancel an appointment

    You cannot:
     - amend a patient's appointments beyond cancelling
     - re-schedule a patient's appointments (this must be done by cancelling and re-booking)

    To use this API, the end user must be a patient who is:
     - registered with the GP practice
     - registered with NHS login to P9 identity verification level

    ## Who can use this API

    This API can be used by developers of clinical systems. It is a patient-facing API.

    This API:

    - is only intended for use by patient-facing applications
    - can only be used where there is a legal basis to do so

    Make sure you have a valid use case before you go too far with your development. To do this, contact us.

    You must do this before you can go live (see 'Onboarding' below).

    ### Prerequisites

    Information governance (IG)

     You must:

     - be compliant with the GP Connect Direct Care API Information Governance Model

     - manage access to your system locally using local role-based access control (RBAC). This does not need to be compliant with the national RBAC model and GP Connect products do not require smartcards to control access, though they can be used if already implementedbe using the GP Connect APIs for direct care purposes for NHS patients in England


    Clinical safety

    You must:

    - have a clinical safety officer (CSO) who is responsible for DCB0129 and, if necessary, DCB0160. For more on clinical risk management, visit Clinical risk management standards.

    If you are confident that you can meet the prerequisites, contact us to express your interest. See 'Onboarding' below.

    ## Related APIs

      The following APIs are related to this API:

      [GP Connect Access Document - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-document-fhir) - retrieve unstructured documents from a patient's GP practice record.

      [GP Connect Access Record: HTML - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-record-html-fhir) - view a patient's GP practice record, with read-only access.

      [GP Connect Access Record: Structured - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-access-record-structured-fhir) - retrieve structured information from a patient's GP practice record.

      [GP Connect Appointment Management - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-appointment-management-fhir) - manage GP practice appointments between different systems.

      [GP Connect Send Document - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-send-document-fhir) - send a PDF consultation summary to a registered GP practice.

      [GP Connect (Patient Facing) Access Record - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-patient-facing-access-record-fhir) - access a patient's GP records with the GP Connect (patient facing) Access Record - FHIR API.

      [GP Connect (Patient Facing) Appointment Management - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-patient-facing-appointment-management-fhir) - manage a patient's GP appointments using the GP Connect (patient facing) Appointment Management - FHIR API.

      [GP Connect (Patient Facing) Prescriptions - FHIR API](https://digital.nhs.uk/developer/api-catalogue/gp-connect-patient-facing-prescriptions-fhir) - manage a patient's prescriptions using the GP Connect (patient facing) Prescriptions - FHIR API.

    ## API status and roadmap

    This API (v1.0) is in [development](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).

    ## Service level

    This API is a silver service, meaning it is operational 24 x 7 x 365 but only supported during business hours (8am to 6pm), Monday to Friday excluding bank holidays.

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology

    This API is a FHIR API.

    It sends a FHIR STU3 payload.

    For more details, see [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#fhir).

    ## Network access

    This API is available on the internet and indirectly over HSCN.

    For more details, see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation

    This API is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present and authenticated to use it.

    The end user must be:

    - a patient

    - authenticated with NHS login to P9 identity verification level

    The API uses Open ID Connect to authenticate the end user and OAuth 2.0 to authorise the calling system. It supports the following security pattern using NHS login:

    [User-restricted RESTful APIs - NHS login separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation)

    ## Environments and testing

    | Purpose          | URL                                                   |
    | -------          | ---                                                   |
    | Sandbox          | `https://sandbox.api.service.nhs.uk/gp-connect/patient-facing/appointments-management-fhir.
    | Integration test | Not yet available                                     |
    | Production       | Not yet available                                     |

    ### Sandbox testing

    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):

    - is for early developer testing
    - only covers a limited set of scenarios
    - is stateless, so it does not store data
    - is open access, so does not allow you to test authorisation

    For more details on sandbox testing, or to try out the sandbox using our
    "Try this API\" feature, see the documentation for each endpoint.

    ### Integration testing (not yet available)

    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):

    - is for formal integration testing
    - is stateful, so it does persist data
    - includes authorisation

    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).

    ## Errors

    We use standard HTTP status codes to show whether an API request succeeded
    or not. They are usually in the range:

    - 200 to 299 if it succeeded, including code 202 if it was accepted by an
    API that needs to wait for further action

    - 400 to 499 if it failed because of a client error by your application

    - 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.
    API Specific errors can be found [here.](https://simplifier.net/guide/pfs-appointments/guides-pfs-appointments-home-build-error-handling?version=current)


    ## Onboarding

    This API is not yet available for onboarding.

    ### Expressing an interest

    If you meet the prerequisites and have a product that can integrate with GP Connect, you should express an interest with us by submitting a use case.

    The main purpose of the use case is to help us understand how you plan to use GP Connect APIs and the business issue you are looking to address. You should email your use case to us at gpconnect@nhs.net.

    Your use case should include the following information as a minimum:

    - the business problem you are intending to solve using GP wConnect
    - how GP Connect will be used in practice to benefit patients and staff
    - which of the GP Connect products you will use to benefit patients and staff
    - any end user organisations you are currently working with
    - who your clinical safety officer is and, where available, your clinical risk management process documentation

    Once we receive your use case, we'll respond within 14 days.

    ### Consumer assurance process

    Once we approve your use case, we support you through the assurance process to go live. We will discuss the assurance process and artefacts with you to help you understand our requirements.

    Start your development work within 6 months of use case approval. If you miss this date, a review or new submission of the use case will be required. Changes or additional development will also require a review or new use case submission.

  contact:
    name: gp-connect-appointments-management-fhir API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
servers:
  - description: Sandbox environment.
    url: https://sandbox.api.service.nhs.uk/gp-connect-appointments-management-fhir
  - description: Integration test environment.
    url: https://int.api.service.nhs.uk/gp-connect-appointments-management-fhir
  - description: Production environment.
    url: https://api.service.nhs.uk/gp-connect-appointments-management-fhir
paths:
  /FHIR/STU3/patient/{id}/appointment:
    get:
      tags:
        - Appointment Management
      summary: Read a patient's appointments
      parameters:
        - $ref: "#/components/parameters/BearerAuthorization"
        - $ref: "#/components/parameters/CorrelationID"
        - $ref: "#/components/parameters/RequestID"
        - name: id
          in: path
          description: The patient's NHS number. The primary identifier of a patient, unique within NHS England and Wales. Always 10 digits and must be a [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
          required: true
          schema:
            type: string
          example: '9000000009'
        - name: start
          in: query
          description: Appointment start/end dates. Default values show a query for appointments on or after 2020-05-09 and on or before 2020-05-19.
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
            default: ["ge2020-05-09","le2020-05-19"]
      responses:
        '200':
          description: OK
          content:
            application/fhir+json:
              schema:
                type: object
              examples:
                example:
                  value:
                    resourceType: Bundle
                    type: searchset
                    entry:
                      - resource:
                          resourceType: Appointment
                          id: '149'
                          meta:
                            versionId: '1503310820000'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
                          contained:
                            - resourceType: Organization
                              id: '1'
                              meta:
                                profile:
                                  - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                              identifier:
                                - system: https://fhir.nhs.uk/Id/ods-organization-code
                                  value: A00123
                              type:
                                - coding:
                                    - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                                      code: gp-practice
                              name: West Road GP Practice
                              telecom:
                                - system: phone
                                  value: '03003035678'
                          extension:
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                              valueReference:
                                reference: '#1'
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1
                              valueCodeableConcept:
                                coding:
                                  - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1
                                    code: R0600
                                    display: Specialist Nurse Practitioner
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                              valueCode: In-person
                          status: booked
                          serviceCategory:
                            text: Nurse Appointments
                          serviceType:
                            - text: Nurse Appointment
                          description: GP Connect Appointment description 148
                          start: '2017-08-21T10:30:00+01:00'
                          end: '2017-08-21T10:50:00+01:00'
                          minutesDuration: 20
                          slot:
                            - reference: Slot/544
                            - reference: Slot/545
                          created: '2017-07-09T13:48:41+01:00'
                          comment: Test Appointment Comment 148
                          participant:
                            - actor:
                                reference: Patient/9000000009
                              status: accepted
                            - actor:
                                reference: Location/1
                              status: accepted
                            - actor:
                                reference: Practitioner/2
                              status: accepted
                      - resource:
                          resourceType: Appointment
                          id: '150'
                          meta:
                            versionId: '1503440820000'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
                          contained:
                            - resourceType: Organization
                              id: '1'
                              meta:
                                profile:
                                  - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                              identifier:
                                - system: https://fhir.nhs.uk/Id/ods-organization-code
                                  value: Z100
                              type:
                                - coding:
                                    - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                                      code: GP Practice
                              name: DR P Stamp
                              telecom:
                                - system: phone
                                  value: '01111222333'
                          extension:
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                              valueReference:
                                reference: '#1'
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1
                              valueCodeableConcept:
                                coding:
                                  - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1
                                    code: R0260
                                    display: General Medical Practitioner
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                              valueCode: In-person
                          status: booked
                          serviceCategory:
                            text: General GP Appointments
                          serviceType:
                            - text: General GP Appointment
                          description: GP Connect Appointment description 148
                          start: '2017-08-17T11:20:00+01:00'
                          end: '2017-08-17T11:30:00+01:00'
                          minutesDuration: 10
                          slot:
                            - reference: Slot/303
                          created: '2017-08-14T13:48:41+01:00'
                          participant:
                            - actor:
                                reference: Patient/9000000009
                              status: accepted
                            - actor:
                                reference: Location/1
                              status: accepted
  /FHIR/STU3/Slot:
    get:
      tags:
        - Appointment Management
      summary: Search for free slots
      parameters:
        - $ref: "#/components/parameters/BearerAuthorization"
        - $ref: "#/components/parameters/CorrelationID"
        - $ref: "#/components/parameters/RequestID"
        - name: start
          in: query
          description: Slot start date/time
          required: true
          schema:
            type: string
          example: ge2020-05-09
        - name: end
          in: query
          description: Slot end date/time
          required: true
          schema:
            type: string
          example: le2020-05-10
        - name: status
          in: query
          description: Slot status
          required: true
          schema:
            type: string
            default: free
            enum:
              - free
        - name: _include
          in: query
          description: Include
          required: true
          schema:
            type: string
            default: Slot:schedule
            enum:
              - Slot:schedule
        - name: _include:recurse
          in: query
          description: Include recurse
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - Schedule:actor:Practitioner
                - Schedule:actor:Location
                - Location:managingOrganization
        - name: searchFilter
          in: query
          description: Search filter
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - >-
                  https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1|gp-practice
                - >-
                  https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1|urgent-care
                - https://fhir.nhs.uk/Id/ods-organization-code|A20047
      responses:
        '200':
          description: OK
          content:
            application/fhir+json:
              schema:
                type: object
              examples:
                example:
                  value:
                    resourceType: Bundle
                    type: searchset
                    entry:
                      - resource:
                          resourceType: Slot
                          id: '1584'
                          meta:
                            versionId: '1471219260000'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Slot-1
                          extension:
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                              valueCode: In-person
                          serviceType:
                            - text: General GP Appointment
                          schedule:
                            reference: Schedule/14
                          status: free
                          start: '2016-08-15T11:30:00+01:00'
                          end: '2016-08-15T11:40:00+01:00'
                      - resource:
                          resourceType: Slot
                          id: '1644'
                          meta:
                            versionId: '1471219260112'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Slot-1
                          extension:
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                              valueCode: In-person
                          serviceType:
                            - text: NHS Health Check
                          schedule:
                            reference: Schedule/14
                          status: free
                          start: '2016-08-15T11:40:00+01:00'
                          end: '2016-08-15T11:50:00+01:00'
                      - resource:
                          resourceType: Schedule
                          id: '14'
                          meta:
                            versionId: '1469444400000'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Schedule-1
                          extension:
                            - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1
                              valueCodeableConcept:
                                coding:
                                  - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1
                                    code: R0260
                                    display: General Medical Practitioner
                          serviceCategory:
                            text: General GP Appointments
                          actor:
                            - reference: Location/17
                            - reference: Practitioner/2
                          planningHorizon:
                            start: '2016-08-15T09:00:00+01:00'
                            end: '2016-08-15T12:00:00+01:00'
                      - resource:
                          resourceType: Practitioner
                          id: '2'
                          meta:
                            versionId: '636064088099800115'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Practitioner-1
                          identifier:
                            - system: https://fhir.nhs.uk/Id/sds-user-id
                              value: '111122223333'
                          name:
                            - family: Black
                              given:
                                - Sarah
                              prefix:
                                - Mrs
                          gender: female
                      - resource:
                          resourceType: Location
                          id: '17'
                          meta:
                            versionId: '636064088100870233'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Location-1
                          name: The Trevelyan Practice
                          address:
                            line:
                              - Trevelyan Square
                              - Boar Ln
                              - Leeds
                            postalCode: LS1 6AE
                          telecom:
                            system: phone
                            value: '03003035678'
                            use: work
                          managingOrganization:
                            reference: Organization/23
                      - resource:
                          resourceType: Organization
                          id: '23'
                          meta:
                            versionId: '636064088098730113'
                            profile:
                              - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                          identifier:
                            - system: https://fhir.nhs.uk/Id/ods-organization-code
                              value: A00001
                          name: The Trevelyan Practice
                          address:
                            line:
                              - Trevelyan Square
                              - Boar Ln
                            city: Leeds
                            district: West Yorkshire
                            postalCode: LS1 6AE
                          telecom:
                            system: phone
                            value: '03003035678'
                            use: work
  /FHIR/STU3/Appointment:
    post:
      tags:
        - Appointment Management
      summary: Book an appointment
      parameters:
        - $ref: "#/components/parameters/BearerAuthorization"
        - $ref: "#/components/parameters/CorrelationID"
        - $ref: "#/components/parameters/RequestID"
      requestBody:
        description: Appointment
        content:
          application/fhir+json:
            schema:
              type: object
            example:
              resourceType: Appointment
              meta:
                 profile:
                       - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
              contained:
                     - resourceType: Organization
                       id: '1'
                       meta:
                         profile:
                           - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                       identifier:
                         - system: https://fhir.nhs.uk/Id/ods-organization-code
                           value: Z100
                       type:
                         - coding:
                             - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                               code: GP Practice
                       name: Dr P. Stamp
                       telecom:
                         - system: phone
                           value: '01111222333'
                           extension:
                           - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                       valueReference:
                         reference: '#1'
                         status: proposed
                         description: Free text description.
                         start: '2017-05-30T10:00:00+01:00'
                         end: '2017-05-30T10:25:00+01:00'
                         slot:
                         - reference: Slot/1
                         created: '2017-05-25T13:48:41+01:00'
                         comment: Free text comment.
                         participant:
                     - actor:
                         reference: Patient/9000000009
                       status: accepted
                     - actor:
                         reference: Location/32
                       status: accepted
                       required: true
      responses:
        '201':
          description: Created
          content:
            application/fhir+json:
              schema:
                type: object
              example:
                resourceType: Appointment
                id: '9'
                meta:
                  versionId: '636068818095315079'
                  profile:
                    - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
                contained:
                  - resourceType: Organization
                    id: '1'
                    meta:
                      profile:
                        - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                    identifier:
                      - system: https://fhir.nhs.uk/Id/ods-organization-code
                        value: Z100
                    type:
                      - coding:
                          - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                            code: GP Practice
                    name: Dr P.Stamp
                    telecom:
                      - system: phone
                        value: '01111222333'
                extension:
                  - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                    valueReference:
                      reference: '#1'
                  - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1
                    valueCodeableConcept:
                      coding:
                        - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1
                          code: R0260
                          display: General Medical Practitioner
                  - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                    valueCode: In-person
                status: booked
                serviceCategory:
                  text: General GP Appointments
                serviceType:
                  - text: General GP Appointment
                description: Free text description.
                start: '2017-05-30T10:00:00+01:00'
                end: '2017-05-30T10:25:00+01:00'
                minutesDuration: 25
                slot:
                  - reference: Slot/1
                created: '2017-05-25T13:48:41+01:00'
                comment: Free text comment.
                participant:
                  - actor:
                      reference: Patient/9000000009
                    status: accepted
                  - actor:
                      reference: Location/32
                    status: accepted
      x-codegen-request-body-name: body
  /FHIR/STU3/Appointment/{id}:
    get:
      tags:
        - Appointment Management
      summary: Get details of a single appointment
      parameters:
        - $ref: "#/components/parameters/BearerAuthorization"
        - $ref: "#/components/parameters/CorrelationID"
        - $ref: "#/components/parameters/RequestID"
        - name: id
          in: path
          description: Appointment logical identifier
          required: true
          schema:
            type: string
          example: '1'
      responses:
        '200':
          description: OK
          content:
            application/fhir+json:
              schema:
                type: object
              examples:
                example:
                  value:
                    resourceType: Appointment
                    id: '150'
                    meta:
                      versionId: '1503440820000'
                      profile:
                        - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
                    contained:
                      - resourceType: Organization
                        id: '1'
                        meta:
                          profile:
                            - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                        identifier:
                          - system: https://fhir.nhs.uk/Id/ods-organization-code
                            value: Z100
                        type:
                          - coding:
                              - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                                code: GP Practice
                        name: Dr P. Stamp
                        telecom:
                          - system: phone
                            value: '01111222333'
                    extension:
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                        valueReference:
                          reference: '#1'
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1
                        valueCodeableConcept:
                          coding:
                            - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1
                              code: R0260
                              display: General Medical Practitioner
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                        valueCode: In-person
                    status: booked
                    serviceCategory:
                      text: General GP Appointments
                    serviceType:
                      - text: General GP Appointment
                    description: GP Connect Appointment description 148
                    start: '2017-08-17T11:20:00+01:00'
                    end: '2017-08-17T11:30:00+01:00'
                    minutesDuration: 10
                    slot:
                      - reference: Slot/303
                    created: '2017-08-14T13:48:41+01:00'
                    participant:
                      - actor:
                          reference: Patient/9000000009
                        status: accepted
                      - actor:
                          reference: Location/1
                        status: accepted
    put:
      tags:
        - Appointment Management
      summary: Cancel an appointment
      parameters:
        - $ref: "#/components/parameters/BearerAuthorization"
        - $ref: "#/components/parameters/CorrelationID"
        - $ref: "#/components/parameters/RequestID"
        - name: id
          in: path
          description: Appointment logical identifier
          required: true
          schema:
            type: string
          example: '1'
      requestBody:
        description: Appointment
        content:
          application/fhir+json:
            schema:
              type: object
            example:
              resourceType: Appointment
              id: '9'
              meta:
                versionId: '636068818095315079'
                profile:
                  - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
              contained:
                - resourceType: Organization
                  id: '1'
                  meta:
                    profile:
                      - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                  identifier:
                    - system: https://fhir.nhs.uk/Id/ods-organization-code
                      value: A00001
                  type:
                    - coding:
                        - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                          code: gp-practice
                  name: West Road GP Practice
                  telecom:
                    - system: phone
                      value: 0300303 5678
              extension:
                - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                  valueReference:
                    reference: '#1'
                - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-AppointmentCancellationReason-1
                  valueString: Free text cancellation reason.
              status: cancelled
              description: Free text description updated.
              start: '2017-05-30T10:00:00+01:00'
              end: '2017-05-30T10:25:00+01:00'
              slot:
                - reference: Slot/1
              created: '2017-05-25T13:48:41+01:00'
              comment: Free text comment.
              participant:
                - actor:
                    reference: Patient/9000000009
                  status: accepted
                - actor:
                    reference: Location/32
                  status: accepted
      responses:
        '200':
          description: OK
          content:
            application/fhir+json:
              schema:
                type: object
              examples:
                example:
                  value:
                    resourceType: Appointment
                    id: '9'
                    meta:
                      versionId: '636068818095315079'
                      profile:
                        - https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Appointment-1
                    contained:
                      - resourceType: Organization
                        id: '1'
                        meta:
                          profile:
                            - https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-Organization-1
                        identifier:
                          - system: https://fhir.nhs.uk/Id/ods-organization-code
                            value: A00001
                        type:
                          - coding:
                              - system: https://fhir.nhs.uk/STU3/CodeSystem/GPConnect-OrganisationType-1
                                code: gp-practice
                        name: West Road GP Practice
                        telecom:
                          - system: phone
                            value: 0300 303 5678
                    extension:
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-BookingOrganisation-1
                        valueReference:
                          reference: '#1'
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-AppointmentCancellationReason-1
                        valueString: Free text cancellation reason.
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-PractitionerRole-1
                        valueCodeableConcept:
                          coding:
                            - system: https://fhir.nhs.uk/STU3/CodeSystem/CareConnect-SDSJobRoleName-1
                              code: R0260
                              display: General Medical Practitioner
                      - url: https://fhir.nhs.uk/STU3/StructureDefinition/Extension-GPConnect-DeliveryChannel-2
                        valueCode: In-person
                    status: cancelled
                    serviceCategory:
                      text: General GP Appointments
                    serviceType:
                      - text: General GP Appointment
                    description: Free text description updated.
                    start: '2017-05-30T10:00:00+01:00'
                    end: '2017-05-30T10:25:00+01:00'
                    minutesDuration: 10
                    slot:
                      - reference: Slot/1
                    created: '2017-05-25T13:48:41+01:00'
                    comment: Free text comment.
                    participant:
                      - actor:
                          reference: Patient/9000000009
                        status: accepted
                      - actor:
                          reference: Location/32
                        status: accepted

      x-codegen-request-body-name: body
components:
  parameters:
    BearerAuthorization:
      in: header
      name: Authorization
      description: |
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).
        Required in all environments except sandbox.
      required: true
      schema:
        type: string
        format: '^Bearer\ [[:ascii:]]+$'
        example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'
    RoleId:
      in: header
      name: NHSD-Session-URID
      description: |
        The user role ID (URID) for the current session. Also known as a user role profile ID (URPID).
        If you are using User-restricted RESTful APIs - NHS login separate authentication and authorisation, see [determine the user's role](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-cis2-separate-authentication-and-authorisation#step-9-determine-the-user-s-role) for guidance.
        This field is optional.
      required: false
      schema:
        type: string
        pattern: '^[0-9]+$'
        example: '555254240100'
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: |
        An optional ID which you can use to track transactions across multiple systems. It can have any value, but we recommend avoiding `.` characters.
        Mirrored back in a response header.
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    RequestID:
      in: header
      name: X-Request-ID
      required: true
      description: |
        A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests and to trace the request if you contact our helpdesk.
        Must be a universally unique identifier (UUID) (ideally version 4).

        Mirrored back in a response header.

        If you re-send a failed request, use the same value in this header.

        Required in all environments except sandbox.
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
